mod MESSAGE is
    protecting INT .
    protecting STRING .
    including CONFIGURATION .

    sorts MsgCont .

    op send_from_to_ : MsgCont Oid Oid -> Msg [ctor] .

    ops copy ack : -> MsgCont [ctor] .

    op cont : Msg -> MsgCont .
    op dest : Msg -> Oid .
    op src : Msg -> Oid .

    var M : Msg .
    var C : MsgCont .
    vars N1 N2 : Oid .

    eq cont(send C from N1 to N2) = C .
    eq src(send C from N1 to N2) = N1 .
    eq dest(send C from N1 to N2) = N2 .

endm